#!/bin/bash

# Essex Wolf | 2016 
# ddig v1.5.0  | 2019-10-24
# https://github.com/tailwag/ddig

SITE=$(echo $1 | sed 's|https\?://||g' | awk -F "/" '{print $1}')
NASS=$2
IFS="\`"

GERP=$(echo ${SITE} | grep -Eo "([1-2]?[0-9]{1,2}\.){3}[1-2]?[0-9]{1,2}")
if [[ "x${GERP}" == "x" ]]; then 
	RAD=$(dig +short "${SITE}" | grep -Eo "([1-2]?[0-9]{1,2}\.){3}[1-2]?[0-9]{1,2}")
else 
	RAD=$SITE
fi
for type in {A,AAAA,NS,CNAME,rDNS,SOA,MX,TXT}; do 
	if [[ "${type}" == "rDNS" ]]; then 
		DIG=$(dig +short -x ${NASS} ${RAD} 2> /dev/null)
	else 
		DIG=$(dig +short ${type} ${NASS} ${SITE} 2> /dev/null)
	fi
	COUNT=1
	for i in $(echo ${DIG} | sed ':a;N;$!ba;s/\n/\`/g'); do 
		printf "%-7s:%2s\n" "${type}" "  ${i}"
		type=""
	done 
	if [[ "x${DIG}" != "x" ]]; then printf "\n"; fi
done
